### ISSUE TITLE
Review Needed

### ISSUE THREAD

**Issue by fabienogli** [PolytechLyon/isi3-tp2-visiteur-kpamy-ogli-tp2#1]

**Comment by Slashgear** [comment]
- rapport simple et efficace

- Un rangement en package (nom de package en minuscule)

- La priorité sous forme int c'est pas mal mais pour éviter les "magiques numbers" qui donnent pas de sens. On pourrait envisager un ENUM valué ? 

- Pouvez vous m'expliquer quand implémenter un visiteur ?

**Comment by fabienogli** [comment]
On implémente le pattern visiteur lorsque l'on veut ajouter des opérations à des classes (ici Negation, Constante, Multiplication et Addition) sans modifier leur structures.

**Comment by Slashgear** [comment]
J'aimerais un peu plus d'explication. Désolé je suis chiant mais c'est pour votre bien.

Normalement votre explication devrait contenir des expressions comme

"Type concrèts", "Traitements" "Type Abstraits" "Ouvert Fermé"

**Comment by markkpamy** [comment]
Le pattern visiteur permet de déﬁnir de nouvelles opérations sur les éléments d’une structure sans changer les classes des éléments sur lesquels on effectue ces traitements. Cela permet de mettre en place un traitement adapté pour chaque objet concerné.
En termes de POO, le fait de migrer des opérations contenues dans une classe vers une autre n'est pas recommandé car l'ajout ou la modification d'une classe n’entraînerait pas l'adaptation des visiteurs existants. Le pattern visiteur est donc utile lorsqu'on a un ensemble de classes fermées  et que l'on veut effectuer un nouveau traitement sur ces classes. L'avantage du patron visiteur est qu'un visiteur peut avoir un état. Ce qui signifie que le traitement d'un type d'objet peut différer en fonction de traitements précédents. 
Pour implémenter une opération, il faut déﬁnir une classe qui implémente **Visitor** et qui regroupe les diﬀérentes actions de cette opération pour chaque type concret d’élément (**ConcreteElement**).

**Comment by Slashgear** [comment]
👌
